### ISSUE TITLE
.tek_cache get confused when files from a subdirectory is included

### ISSUE THREAD

**Issue by lilulu** [palmer-dabbelt/tek#4]
Currently tek supports including a file from the current directory (see first /input in the attached sample file), including images from the current directory and sub-directories (not included in the sample file but from previous experience). But tek does not correctly interpret including a file from a sub-directory (see second /input in the attached sample file). Running 'tek;make' in the attached case generate the following error: 

make: *** No rule to make target '.tek_cache/chapters/chapter.stex-stexdeps', needed by '.tek_cache/chapters/chapter.stex'.  Stop.
make: *** Waiting for unfinished jobs....

If I understand this correctly, what appears to be happening is that there are inconsistency between what the Makefile think the included file is (.tek_cache/chapters/chapter.stex) and where the file actually lives (chapters/.tek_cache/chapters.tex). I could be wrong though.
[tek-case1.zip](https://github.com/palmer-dabbelt/tek/files/374912/tek-case1.zip)

**Comment by palmer-dabbelt** [comment]
Fixed by https://github.com/palmer-dabbelt/tek/commit/1d353fee7682617c9a5cf42671e0ef1b2ec95810
